/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result, EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type IncentiveKeyStruct = {
  rewardToken: string;
  pool: string;
  startTime: BigNumberish;
  endTime: BigNumberish;
};

export type IncentiveKeyStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber
] & {
  rewardToken: string;
  pool: string;
  startTime: BigNumber;
  endTime: BigNumber;
};

export interface Ad3StakeManagerInterface extends utils.Interface {
  functions: {
    "acceptGoverance()": FunctionFragment;
    "cancelIncentive((address,address,uint256,uint256),address)": FunctionFragment;
    "claimReward((address,address,uint256,uint256),uint256,address,uint256)": FunctionFragment;
    "createIncentive((address,address,uint256,uint256),uint256,int24,int24)": FunctionFragment;
    "deployer()": FunctionFragment;
    "depositToken((address,address,uint256,uint256),uint256)": FunctionFragment;
    "deposits(uint256)": FunctionFragment;
    "factory()": FunctionFragment;
    "getAccruedRewardInfo((address,address,uint256,uint256),uint256)": FunctionFragment;
    "getTokenId(uint256)": FunctionFragment;
    "getTokenIdCount()": FunctionFragment;
    "getUserTokenIdCount(address)": FunctionFragment;
    "gov()": FunctionFragment;
    "incentives(bytes32)": FunctionFragment;
    "initialize(address,address,address)": FunctionFragment;
    "nextgov()": FunctionFragment;
    "nonfungiblePositionManager()": FunctionFragment;
    "onERC721Received(address,address,uint256,bytes)": FunctionFragment;
    "rewards(address,address)": FunctionFragment;
    "setGoverance(address)": FunctionFragment;
    "stakes(bytes32,uint256)": FunctionFragment;
    "unstakeToken((address,address,uint256,uint256),uint256,address)": FunctionFragment;
    "updateRange((address,address,uint256,uint256),int24,int24)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptGoverance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelIncentive",
    values: [IncentiveKeyStruct, string]
  ): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values: [IncentiveKeyStruct, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createIncentive",
    values: [IncentiveKeyStruct, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "depositToken",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAccruedRewardInfo",
    values: [IncentiveKeyStruct, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenIdCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTokenIdCount",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "gov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "incentives",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(functionFragment: "nextgov", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nonfungiblePositionManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "onERC721Received",
    values: [string, string, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rewards",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setGoverance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "stakes",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeToken",
    values: [IncentiveKeyStruct, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateRange",
    values: [IncentiveKeyStruct, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGoverance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIncentive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccruedRewardInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTokenId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenIdCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTokenIdCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gov", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "incentives", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextgov", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nonfungiblePositionManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "onERC721Received",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewards", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGoverance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unstakeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateRange",
    data: BytesLike
  ): Result;

  events: {
    "IncentiveCanceled(bytes32,uint256)": EventFragment;
    "IncentiveCreated(address,address,uint256,uint256,uint256)": EventFragment;
    "RewardClaimed(address,uint256)": EventFragment;
    "TokenReceived(uint256,address)": EventFragment;
    "TokenStaked(bytes32,uint256,uint128)": EventFragment;
    "TokenUnstaked(bytes32,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "IncentiveCanceled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "IncentiveCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RewardClaimed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenReceived"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenStaked"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenUnstaked"): EventFragment;
}

export type IncentiveCanceledEvent = TypedEvent<
  [string, BigNumber],
  { incentiveId: string; rewardUnclaimed: BigNumber }
>;

export type IncentiveCanceledEventFilter =
  TypedEventFilter<IncentiveCanceledEvent>;

export type IncentiveCreatedEvent = TypedEvent<
  [string, string, BigNumber, BigNumber, BigNumber],
  {
    rewardToken: string;
    pool: string;
    startTime: BigNumber;
    endTime: BigNumber;
    reward: BigNumber;
  }
>;

export type IncentiveCreatedEventFilter =
  TypedEventFilter<IncentiveCreatedEvent>;

export type RewardClaimedEvent = TypedEvent<
  [string, BigNumber],
  { to: string; reward: BigNumber }
>;

export type RewardClaimedEventFilter = TypedEventFilter<RewardClaimedEvent>;

export type TokenReceivedEvent = TypedEvent<
  [BigNumber, string],
  { tokenId: BigNumber; owner: string }
>;

export type TokenReceivedEventFilter = TypedEventFilter<TokenReceivedEvent>;

export type TokenStakedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  { incentiveId: string; tokenId: BigNumber; liquidity: BigNumber }
>;

export type TokenStakedEventFilter = TypedEventFilter<TokenStakedEvent>;

export type TokenUnstakedEvent = TypedEvent<
  [string, BigNumber],
  { incentiveId: string; tokenId: BigNumber }
>;

export type TokenUnstakedEventFilter = TypedEventFilter<TokenUnstakedEvent>;

export interface Ad3StakeManager extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Ad3StakeManagerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptGoverance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    cancelIncentive(
      key: IncentiveKeyStruct,
      refundee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    claimReward(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      minTick: BigNumberish,
      maxTick: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deployer(overrides?: CallOverrides): Promise<[string]>;

    depositToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    deposits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number, number] & {
        owner: string;
        numberOfStakes: BigNumber;
        tickLower: number;
        tickUpper: number;
      }
    >;

    factory(overrides?: CallOverrides): Promise<[string]>;

    getAccruedRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        reward: BigNumber;
        secondsInsideX128: BigNumber;
        secondsPerLiquidityInsideX128: BigNumber;
      }
    >;

    "getTokenId(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenId: BigNumber }>;

    "getTokenId(address,uint256)"(
      to: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { tokenId: BigNumber }>;

    getTokenIdCount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { index: BigNumber }>;

    getUserTokenIdCount(
      to: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    gov(overrides?: CallOverrides): Promise<[string]>;

    incentives(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number, number] & {
        totalRewardUnclaimed: BigNumber;
        totalSecondsClaimedX128: BigNumber;
        numberOfStakes: BigNumber;
        minTick: number;
        maxTick: number;
      }
    >;

    initialize(
      _gov: string,
      _factory: string,
      _nonfungiblePositionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    nextgov(overrides?: CallOverrides): Promise<[string]>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<[string]>;

    onERC721Received(
      arg0: string,
      operator: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rewards(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setGoverance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    stakes(
      incentiveId: BytesLike,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        owner: string;
        liquidity: BigNumber;
        secondsPerLiquidityInsideInitialX128: BigNumber;
        secondsPerLiquidityInsideAccruedX128: BigNumber;
      }
    >;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRange(
      key: IncentiveKeyStruct,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptGoverance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  cancelIncentive(
    key: IncentiveKeyStruct,
    refundee: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  claimReward(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    to: string,
    amountRequested: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  createIncentive(
    key: IncentiveKeyStruct,
    reward: BigNumberish,
    minTick: BigNumberish,
    maxTick: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deployer(overrides?: CallOverrides): Promise<string>;

  depositToken(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  deposits(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, number, number] & {
      owner: string;
      numberOfStakes: BigNumber;
      tickLower: number;
      tickUpper: number;
    }
  >;

  factory(overrides?: CallOverrides): Promise<string>;

  getAccruedRewardInfo(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber] & {
      reward: BigNumber;
      secondsInsideX128: BigNumber;
      secondsPerLiquidityInsideX128: BigNumber;
    }
  >;

  "getTokenId(uint256)"(
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "getTokenId(address,uint256)"(
    to: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getTokenIdCount(overrides?: CallOverrides): Promise<BigNumber>;

  getUserTokenIdCount(
    to: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  gov(overrides?: CallOverrides): Promise<string>;

  incentives(
    arg0: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, number, number] & {
      totalRewardUnclaimed: BigNumber;
      totalSecondsClaimedX128: BigNumber;
      numberOfStakes: BigNumber;
      minTick: number;
      maxTick: number;
    }
  >;

  initialize(
    _gov: string,
    _factory: string,
    _nonfungiblePositionManager: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  nextgov(overrides?: CallOverrides): Promise<string>;

  nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

  onERC721Received(
    arg0: string,
    operator: string,
    tokenId: BigNumberish,
    data: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rewards(
    arg0: string,
    arg1: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setGoverance(
    _gov: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  stakes(
    incentiveId: BytesLike,
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, BigNumber] & {
      owner: string;
      liquidity: BigNumber;
      secondsPerLiquidityInsideInitialX128: BigNumber;
      secondsPerLiquidityInsideAccruedX128: BigNumber;
    }
  >;

  unstakeToken(
    key: IncentiveKeyStruct,
    tokenId: BigNumberish,
    to: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRange(
    key: IncentiveKeyStruct,
    tickLower: BigNumberish,
    tickUpper: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptGoverance(overrides?: CallOverrides): Promise<void>;

    cancelIncentive(
      key: IncentiveKeyStruct,
      refundee: string,
      overrides?: CallOverrides
    ): Promise<void>;

    claimReward(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      amountRequested: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      minTick: BigNumberish,
      maxTick: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deployer(overrides?: CallOverrides): Promise<string>;

    depositToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    deposits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, number, number] & {
        owner: string;
        numberOfStakes: BigNumber;
        tickLower: number;
        tickUpper: number;
      }
    >;

    factory(overrides?: CallOverrides): Promise<string>;

    getAccruedRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        reward: BigNumber;
        secondsInsideX128: BigNumber;
        secondsPerLiquidityInsideX128: BigNumber;
      }
    >;

    "getTokenId(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokenId(address,uint256)"(
      to: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenIdCount(overrides?: CallOverrides): Promise<BigNumber>;

    getUserTokenIdCount(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<string>;

    incentives(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, number, number] & {
        totalRewardUnclaimed: BigNumber;
        totalSecondsClaimedX128: BigNumber;
        numberOfStakes: BigNumber;
        minTick: number;
        maxTick: number;
      }
    >;

    initialize(
      _gov: string,
      _factory: string,
      _nonfungiblePositionManager: string,
      overrides?: CallOverrides
    ): Promise<void>;

    nextgov(overrides?: CallOverrides): Promise<string>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<string>;

    onERC721Received(
      arg0: string,
      operator: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<string>;

    rewards(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setGoverance(_gov: string, overrides?: CallOverrides): Promise<void>;

    stakes(
      incentiveId: BytesLike,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, BigNumber] & {
        owner: string;
        liquidity: BigNumber;
        secondsPerLiquidityInsideInitialX128: BigNumber;
        secondsPerLiquidityInsideAccruedX128: BigNumber;
      }
    >;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      overrides?: CallOverrides
    ): Promise<void>;

    updateRange(
      key: IncentiveKeyStruct,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "IncentiveCanceled(bytes32,uint256)"(
      incentiveId?: BytesLike | null,
      rewardUnclaimed?: null
    ): IncentiveCanceledEventFilter;
    IncentiveCanceled(
      incentiveId?: BytesLike | null,
      rewardUnclaimed?: null
    ): IncentiveCanceledEventFilter;

    "IncentiveCreated(address,address,uint256,uint256,uint256)"(
      rewardToken?: string | null,
      pool?: string | null,
      startTime?: null,
      endTime?: null,
      reward?: null
    ): IncentiveCreatedEventFilter;
    IncentiveCreated(
      rewardToken?: string | null,
      pool?: string | null,
      startTime?: null,
      endTime?: null,
      reward?: null
    ): IncentiveCreatedEventFilter;

    "RewardClaimed(address,uint256)"(
      to?: string | null,
      reward?: BigNumberish | null
    ): RewardClaimedEventFilter;
    RewardClaimed(
      to?: string | null,
      reward?: BigNumberish | null
    ): RewardClaimedEventFilter;

    "TokenReceived(uint256,address)"(
      tokenId?: BigNumberish | null,
      owner?: string | null
    ): TokenReceivedEventFilter;
    TokenReceived(
      tokenId?: BigNumberish | null,
      owner?: string | null
    ): TokenReceivedEventFilter;

    "TokenStaked(bytes32,uint256,uint128)"(
      incentiveId?: BytesLike | null,
      tokenId?: BigNumberish | null,
      liquidity?: null
    ): TokenStakedEventFilter;
    TokenStaked(
      incentiveId?: BytesLike | null,
      tokenId?: BigNumberish | null,
      liquidity?: null
    ): TokenStakedEventFilter;

    "TokenUnstaked(bytes32,uint256)"(
      incentiveId?: BytesLike | null,
      tokenId?: BigNumberish | null
    ): TokenUnstakedEventFilter;
    TokenUnstaked(
      incentiveId?: BytesLike | null,
      tokenId?: BigNumberish | null
    ): TokenUnstakedEventFilter;
  };

  estimateGas: {
    acceptGoverance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    cancelIncentive(
      key: IncentiveKeyStruct,
      refundee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    claimReward(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      minTick: BigNumberish,
      maxTick: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deployer(overrides?: CallOverrides): Promise<BigNumber>;

    depositToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    deposits(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    factory(overrides?: CallOverrides): Promise<BigNumber>;

    getAccruedRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokenId(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getTokenId(address,uint256)"(
      to: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenIdCount(overrides?: CallOverrides): Promise<BigNumber>;

    getUserTokenIdCount(
      to: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    gov(overrides?: CallOverrides): Promise<BigNumber>;

    incentives(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

    initialize(
      _gov: string,
      _factory: string,
      _nonfungiblePositionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    nextgov(overrides?: CallOverrides): Promise<BigNumber>;

    nonfungiblePositionManager(overrides?: CallOverrides): Promise<BigNumber>;

    onERC721Received(
      arg0: string,
      operator: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rewards(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setGoverance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    stakes(
      incentiveId: BytesLike,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRange(
      key: IncentiveKeyStruct,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGoverance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    cancelIncentive(
      key: IncentiveKeyStruct,
      refundee: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    claimReward(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      amountRequested: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    createIncentive(
      key: IncentiveKeyStruct,
      reward: BigNumberish,
      minTick: BigNumberish,
      maxTick: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deployer(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    depositToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    deposits(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    factory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getAccruedRewardInfo(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokenId(uint256)"(
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getTokenId(address,uint256)"(
      to: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenIdCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getUserTokenIdCount(
      to: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    gov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    incentives(
      arg0: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      _gov: string,
      _factory: string,
      _nonfungiblePositionManager: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    nextgov(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    nonfungiblePositionManager(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    onERC721Received(
      arg0: string,
      operator: string,
      tokenId: BigNumberish,
      data: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rewards(
      arg0: string,
      arg1: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setGoverance(
      _gov: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    stakes(
      incentiveId: BytesLike,
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unstakeToken(
      key: IncentiveKeyStruct,
      tokenId: BigNumberish,
      to: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRange(
      key: IncentiveKeyStruct,
      tickLower: BigNumberish,
      tickUpper: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
